# Generated by Django 3.2.12 on 2022-06-14 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seoul',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'seoul',
            },
        ),
        migrations.CreateModel(
            name='Yongsan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'yongsan',
            },
        ),
        migrations.CreateModel(
            name='Yeongdeungpo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'yeongdeungpo',
            },
        ),
        migrations.CreateModel(
            name='Yangcheon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'yangcheon',
            },
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_chat', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Songpa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'songpa',
            },
        ),
        migrations.CreateModel(
            name='Seongdong',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'seongdong',
            },
        ),
        migrations.CreateModel(
            name='Seongbuk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'seongbuk',
            },
        ),
        migrations.CreateModel(
            name='Seodaemun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'seodaemun',
            },
        ),
        migrations.CreateModel(
            name='Seocho',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'seocho',
            },
        ),
        migrations.CreateModel(
            name='Nowon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'nowon',
            },
        ),
        migrations.CreateModel(
            name='Mapo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'mapo',
            },
        ),
        migrations.CreateModel(
            name='Jungnang',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'jungnang',
            },
        ),
        migrations.CreateModel(
            name='Junggu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'junggu',
            },
        ),
        migrations.CreateModel(
            name='Jongno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'jongno',
            },
        ),
        migrations.CreateModel(
            name='Gwangjin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'gwangjin',
            },
        ),
        migrations.CreateModel(
            name='Gwanak',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'gwanak',
            },
        ),
        migrations.CreateModel(
            name='Guro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'guro',
            },
        ),
        migrations.CreateModel(
            name='Geumcheon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'geumcheon',
            },
        ),
        migrations.CreateModel(
            name='Gangseo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'gangseo',
            },
        ),
        migrations.CreateModel(
            name='Gangnam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'gangnam',
            },
        ),
        migrations.CreateModel(
            name='Gangdong',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'gangdong',
            },
        ),
        migrations.CreateModel(
            name='Gangbuk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'gangbuk',
            },
        ),
        migrations.CreateModel(
            name='Eunpyeong',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'eunpyeong',
            },
        ),
        migrations.CreateModel(
            name='Dongjak',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'dongjak',
            },
        ),
        migrations.CreateModel(
            name='Dongdaemun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'dongdaemun',
            },
        ),
        migrations.CreateModel(
            name='Dobong',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, to='chatting.seoul')),
            ],
            options={
                'db_table': 'dobong',
            },
        ),
    ]
